spring:
  datasource:
    url: jdbc:h2:mem:stock
    username: user
    password:

  h2:
    console:
      enabled: true
      path: /h2

  rabbitmq:
    host: 10.27.1.10
    port: 5672
    username: admin
    password: admin

rabbitmq:
  listen-to: product_queue
  exchange-name: microservice.direct