spring:
  datasource:
    url: jdbc:h2:mem:client
    username: user
    password: pswd
  jpa:
    show-sql: true
  #    hibernate:
  #      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2

